import Sidebar from '../components/Sidebar'
import Homex from '../components/Home'
import styles from '../styles/Home.module.css'
import authorData from '../data/sidebarData'
import Head from 'next/head'

const data = authorData[0]

export default function Home() {
  return (
    <div className={styles.container}>

      <Head>
        <title>julian ☄️</title>
        <meta name="description" content="Generated by create next app" />
      </Head>


      {/* <div className={`${ styles["app"] } flex h-full`}> */}
      <div className={`${styles["app"]} flex h-full`}>

        <Sidebar
          name={data.name}
          description={data.description}
          socials={data.socials}
        />

        <Homex />

      </div>

    </div>
  )
}
